class RecentUser {
  final String? icon, name, date, posts, place, ID, email, password;
  bool? state;
  RecentUser({
    this.icon,
    this.name,
    this.date,
    this.posts,
    this.place,
    this.ID,
    this.email,
    this.password,
    this.state,
  });
}

List recentUsers = [
  RecentUser(
    icon: "assets/icons/xd_file.svg",
    name: "Deniz Çolak",
    ID: "018995",
    email: "Almizan1@shamp.com",
    date: "01-03-2021",
    posts: "4",
    place: "Damascus",
    password: "AlmiZan8754",
    state: true,
  ),
  RecentUser(
    icon: "assets/icons/Figma_file.svg",
    name: "Elaf Oped",
    ID: "018996",
    email: "Almizan2@shamp.com",
    date: "27-02-2021",
    posts: "19",
    place: "Alepo",
    password: "AlmiZan8754",
    state: true,
  ),
  RecentUser(
    icon: "assets/icons/doc_file.svg",
    name: "Anas",
    ID: "465465",
    email: "Almizan3@shamp.com",
    date: "23-02-2021",
    posts: "32",
    place: "Homs",
    password: "AlmiZan8754",
    state: true,
  ),
  RecentUser(
    icon: "assets/icons/sound_file.svg",
    name: "Khaled",
    ID: "656623",
    email: "Almizan4@shamp.com",
    date: "21-02-2021",
    posts: "3",
    place: "Damascus",
    password: "AlmiZan8754",
    state: true,
  ),
  RecentUser(
    icon: "assets/icons/media_file.svg",
    name: "yousf",
    ID: "523265",
    email: "Almizan5@shamp.com",
    date: "23-02-2021",
    posts: "2",
    place: "Homs",
    password: "AlmiZan8754",
    state: true,
  ),
  RecentUser(
    icon: "assets/icons/pdf_file.svg",
    name: "samer",
    ID: "530263",
    email: "Almizan6@shamp.com",
    date: "25-02-2021",
    posts: "3",
    place: "Daraa",
    password: "AlmiZan8754",
    state: true,
  ),
  RecentUser(
    icon: "assets/icons/excle_file.svg",
    name: "ahmed",
    ID: "125487",
    email: "Almizan7@shamp.com",
    date: "25-02-2021",
    posts: "34",
    place: "Hama",
    password: "AlmiZan8754",
    state: true,
  ),
  RecentUser(
    icon: "assets/icons/xd_file.svg",
    name: "Deniz Çolak",
    ID: "018995",
    email: "Almizan1@shamp.com",
    date: "01-03-2021",
    posts: "4",
    place: "Damascus",
    password: "AlmiZan8754",
    state: true,
  ),
  RecentUser(
    icon: "assets/icons/Figma_file.svg",
    name: "Elaf Oped",
    ID: "018996",
    email: "Almizan2@shamp.com",
    date: "27-02-2021",
    posts: "19",
    place: "Alepo",
    password: "AlmiZan8754",
    state: true,
  ),
  RecentUser(
    icon: "assets/icons/doc_file.svg",
    name: "Anas",
    ID: "465465",
    email: "Almizan3@shamp.com",
    date: "23-02-2021",
    posts: "32",
    place: "Homs",
    password: "AlmiZan8754",
    state: true,
  ),
  RecentUser(
    icon: "assets/icons/sound_file.svg",
    name: "Khaled",
    ID: "656623",
    email: "Almizan4@shamp.com",
    date: "21-02-2021",
    posts: "3",
    place: "Damascus",
    password: "AlmiZan8754",
    state: true,
  ),
  RecentUser(
    icon: "assets/icons/media_file.svg",
    name: "yousf",
    ID: "523265",
    email: "Almizan5@shamp.com",
    date: "23-02-2021",
    posts: "2",
    place: "Homs",
    password: "AlmiZan8754",
    state: true,
  ),
  RecentUser(
    icon: "assets/icons/pdf_file.svg",
    name: "samer",
    ID: "530263",
    email: "Almizan6@shamp.com",
    date: "25-02-2021",
    posts: "3",
    place: "Daraa",
    password: "AlmiZan8754",
    state: true,
  ),
  RecentUser(
    icon: "assets/icons/excle_file.svg",
    name: "ahmed",
    ID: "125487",
    email: "Almizan7@shamp.com",
    date: "25-02-2021",
    posts: "34",
    place: "Hama",
    password: "AlmiZan8754",
    state: true,
  ),
  RecentUser(
    icon: "assets/icons/xd_file.svg",
    name: "Deniz Çolak",
    ID: "018995",
    email: "Almizan1@shamp.com",
    date: "01-03-2021",
    posts: "4",
    place: "Damascus",
    password: "AlmiZan8754",
    state: true,
  ),
  RecentUser(
    icon: "assets/icons/Figma_file.svg",
    name: "Elaf Oped",
    ID: "018996",
    email: "Almizan2@shamp.com",
    date: "27-02-2021",
    posts: "19",
    place: "Alepo",
    password: "AlmiZan8754",
    state: true,
  ),
  RecentUser(
    icon: "assets/icons/doc_file.svg",
    name: "Anas",
    ID: "465465",
    email: "Almizan3@shamp.com",
    date: "23-02-2021",
    posts: "32",
    place: "Homs",
    password: "AlmiZan8754",
    state: true,
  ),
  RecentUser(
    icon: "assets/icons/sound_file.svg",
    name: "Khaled",
    ID: "656623",
    email: "Almizan4@shamp.com",
    date: "21-02-2021",
    posts: "3",
    place: "Damascus",
    password: "AlmiZan8754",
    state: true,
  ),
  RecentUser(
    icon: "assets/icons/media_file.svg",
    name: "yousf",
    ID: "523265",
    email: "Almizan5@shamp.com",
    date: "23-02-2021",
    posts: "2",
    place: "Homs",
    password: "AlmiZan8754",
    state: true,
  ),
  RecentUser(
    icon: "assets/icons/pdf_file.svg",
    name: "samer",
    ID: "530263",
    email: "Almizan6@shamp.com",
    date: "25-02-2021",
    posts: "3",
    place: "Daraa",
    password: "AlmiZan8754",
    state: true,
  ),
  RecentUser(
    icon: "assets/icons/excle_file.svg",
    name: "ahmed",
    ID: "125487",
    email: "Almizan7@shamp.com",
    date: "25-02-2021",
    posts: "34",
    place: "Hama",
    password: "AlmiZan8754",
    state: true,
  ),
  RecentUser(
    icon: "assets/icons/xd_file.svg",
    name: "Deniz Çolak",
    ID: "018995",
    email: "Almizan1@shamp.com",
    date: "01-03-2021",
    posts: "4",
    place: "Damascus",
    password: "AlmiZan8754",
    state: true,
  ),
  RecentUser(
    icon: "assets/icons/Figma_file.svg",
    name: "Elaf Oped",
    ID: "018996",
    email: "Almizan2@shamp.com",
    date: "27-02-2021",
    posts: "19",
    place: "Alepo",
    password: "AlmiZan8754",
    state: true,
  ),
  RecentUser(
    icon: "assets/icons/doc_file.svg",
    name: "Anas",
    ID: "465465",
    email: "Almizan3@shamp.com",
    date: "23-02-2021",
    posts: "32",
    place: "Homs",
    password: "AlmiZan8754",
    state: true,
  ),
  RecentUser(
    icon: "assets/icons/sound_file.svg",
    name: "Khaled",
    ID: "656623",
    email: "Almizan4@shamp.com",
    date: "21-02-2021",
    posts: "3",
    place: "Damascus",
    password: "AlmiZan8754",
    state: true,
  ),
  RecentUser(
    icon: "assets/icons/media_file.svg",
    name: "yousf",
    ID: "523265",
    email: "Almizan5@shamp.com",
    date: "23-02-2021",
    posts: "2",
    place: "Homs",
    password: "AlmiZan8754",
    state: true,
  ),
  RecentUser(
    icon: "assets/icons/pdf_file.svg",
    name: "samer",
    ID: "530263",
    email: "Almizan6@shamp.com",
    date: "25-02-2021",
    posts: "3",
    place: "Daraa",
    password: "AlmiZan8754",
    state: true,
  ),
  RecentUser(
    icon: "assets/icons/excle_file.svg",
    name: "ahmed",
    ID: "125487",
    email: "Almizan7@shamp.com",
    date: "25-02-2021",
    posts: "34",
    place: "Hama",
    password: "AlmiZan8754",
    state: true,
  ),
  RecentUser(
    icon: "assets/icons/xd_file.svg",
    name: "Deniz Çolak",
    ID: "018995",
    email: "Almizan1@shamp.com",
    date: "01-03-2021",
    posts: "4",
    place: "Damascus",
    password: "AlmiZan8754",
    state: true,
  ),
  RecentUser(
    icon: "assets/icons/Figma_file.svg",
    name: "Elaf Oped",
    ID: "018996",
    email: "Almizan2@shamp.com",
    date: "27-02-2021",
    posts: "19",
    place: "Alepo",
    password: "AlmiZan8754",
    state: true,
  ),
  RecentUser(
    icon: "assets/icons/doc_file.svg",
    name: "Anas",
    ID: "465465",
    email: "Almizan3@shamp.com",
    date: "23-02-2021",
    posts: "32",
    place: "Homs",
    password: "AlmiZan8754",
    state: true,
  ),
  RecentUser(
    icon: "assets/icons/sound_file.svg",
    name: "Khaled",
    ID: "656623",
    email: "Almizan4@shamp.com",
    date: "21-02-2021",
    posts: "3",
    place: "Damascus",
    password: "AlmiZan8754",
    state: true,
  ),
  RecentUser(
    icon: "assets/icons/media_file.svg",
    name: "yousf",
    ID: "523265",
    email: "Almizan5@shamp.com",
    date: "23-02-2021",
    posts: "2",
    place: "Homs",
    password: "AlmiZan8754",
    state: true,
  ),
  RecentUser(
    icon: "assets/icons/pdf_file.svg",
    name: "samer",
    ID: "530263",
    email: "Almizan6@shamp.com",
    date: "25-02-2021",
    posts: "3",
    place: "Daraa",
    password: "AlmiZan8754",
    state: true,
  ),
  RecentUser(
    icon: "assets/icons/excle_file.svg",
    name: "ahmed",
    ID: "125487",
    email: "Almizan7@shamp.com",
    date: "25-02-2021",
    posts: "34",
    place: "Hama",
    password: "AlmiZan8754",
    state: true,
  ),
  RecentUser(
    icon: "assets/icons/xd_file.svg",
    name: "Deniz Çolak",
    ID: "018995",
    email: "Almizan1@shamp.com",
    date: "01-03-2021",
    posts: "4",
    place: "Damascus",
    password: "AlmiZan8754",
    state: true,
  ),
  RecentUser(
    icon: "assets/icons/Figma_file.svg",
    name: "Elaf Oped",
    ID: "018996",
    email: "Almizan2@shamp.com",
    date: "27-02-2021",
    posts: "19",
    place: "Alepo",
    password: "AlmiZan8754",
    state: true,
  ),
  RecentUser(
    icon: "assets/icons/doc_file.svg",
    name: "Anas",
    ID: "465465",
    email: "Almizan3@shamp.com",
    date: "23-02-2021",
    posts: "32",
    place: "Homs",
    password: "AlmiZan8754",
    state: true,
  ),
  RecentUser(
    icon: "assets/icons/sound_file.svg",
    name: "Khaled",
    ID: "656623",
    email: "Almizan4@shamp.com",
    date: "21-02-2021",
    posts: "3",
    place: "Damascus",
    password: "AlmiZan8754",
    state: true,
  ),
  RecentUser(
    icon: "assets/icons/media_file.svg",
    name: "yousf",
    ID: "523265",
    email: "Almizan5@shamp.com",
    date: "23-02-2021",
    posts: "2",
    place: "Homs",
    password: "AlmiZan8754",
    state: true,
  ),
  RecentUser(
    icon: "assets/icons/pdf_file.svg",
    name: "samer",
    ID: "530263",
    email: "Almizan6@shamp.com",
    date: "25-02-2021",
    posts: "3",
    place: "Daraa",
    password: "AlmiZan8754",
    state: true,
  ),
  RecentUser(
    icon: "assets/icons/excle_file.svg",
    name: "ahmed",
    ID: "125487",
    email: "Almizan7@shamp.com",
    date: "25-02-2021",
    posts: "34",
    place: "Hama",
    password: "AlmiZan8754",
    state: true,
  ),
];
